### ISSUE TITLE
Empty value results in (year).(month)...

### ISSUE THREAD

**Issue by domschmidt** [eight04/angular-datetime#39] opened 2016-10-06 07:20 UTC
Hey there,

I really like this library

Starting with version 4.0.0, if the input field value is empty, the field value is something like

![image](https://cloud.githubusercontent.com/assets/5794467/19143664/b98225f8-8ba5-11e6-9931-a6e5aca46d73.png)

This behaviour is really strange. Could you please re-check this decision in 4.0.0 again?

Furthermore, in 4.1.0, even if required/ng-required is set to false, after selecting a date and removing it, the form becomes invalid as the current value (empty) cannot be parsed as a date.

**Comment by eight04** [comment] 2016-10-06 08:32
[Here is the original thread](https://github.com/eight04/angular-datetime/issues/9)

Before version 4.0.0, the value become empty string when the model is null. And here is the behavior what we had:

* Apply current date (or a default value according `default` attr) when the input get focus.  
	Problem: when tabbing through the input, the model changes to a date which is not expected.
* Apply current date (or the default value) when the user try to input anything.  
	Problem: it is confusing to the users since they don't know what to do with the empty input field.
		
Current:

* Each parts of the date is filled with a placeholder when empty. And the model is only valid if all parts are set.  
	Problem: actually it is still confusing. We know we have to input some numbers for `2016-10-06` but what about `(year)-(month)-(date)`?
	
Any better idea? I tend to use second solution and try to indicate the format in `placeholder` attr. Or just always add `required` attr and use a checkbox to decide whether to use that input field.

> current value (empty) cannot be parsed as a date

Confirmed. It will be fixed soon.

**Comment by JanBrinker** [comment] 2016-10-27 12:54
Hi there,
I'm basically having the same issue. I'd also vote for displaying the placeholder until the user tries to enter something. Or alternatively offer an option of defining how the format should look like. That would help localization of websites with your module :)

**Comment by eight04** [comment] 2016-10-29 19:13
Like this?
```
<input ... datetime-placeholder="localizedPlacehold">
```
```
$scope.localizedPlacehold = {
	"year": "...",
	"month": "...",
	...
};
```

@domschmidt
Another problem is the behavior when pressing delete/backspace:

1. Remove all text in the input. `element.val("")`
2. Use a placeholder to replace deleted part just like current behavior.
3. Others... ?

**Comment by domschmidt** [comment] 2016-10-30 15:22
**The proposed solution would be perfect!** 
A localized placeholder variant would be great and would mean that we can migrate to 4.x :-)

**Regarding the backspace button:**
I'd vote for a "natural" feeling:

initial case:
(year)-(month)-(day)

the user enters a date:
2016-10-04
presses backspace
2016-10-0_ (underscore marks the current cursor)
and again
2016-10-_
and again
2016-1_-(day)

and finally, when all parts are removed, the full localized placeholder is shown again

**Comment by JanBrinker** [comment] 2016-10-31 07:40
Sounds good :)
Alternatively the definition of the placeholders could also happen in an initialization step during config. But both ways seem good to me :)

**Comment by eight04** [comment] 2016-11-11 12:27
https://github.com/eight04/angular-datetime/tree/dev-placeholder
http://liveweave.com/lmzSFr
`ng-trim` is required for those formats containing spaces.

**Comment by eight04** [comment] 2016-12-23 03:32
Added at v5.0.0.

Configure it like this:
```
angular
	.module("myApp", ["datetime"])
	.config(function(datetimePlaceholder){
		angular.extend(datetimePlaceholder, {
			year: "<placeholder for year>",
			month: "<placeholder for month>",
			date: "<placeholder for date>"
		});
	});
```
For all valid keys see https://github.com/eight04/angular-datetime#datetimeplaceholder-object

**Closed** 2016-12-23 03:32 UTC

**Comment by cht8687** [comment] 2017-06-05 06:00
Hi, I am just wondering in v5.0.0+, how do we apply current date time when mouse focus on input field if we had set up datetimePlaceholder in .config ?

**Comment by eight04** [comment] 2017-06-05 12:51
Do you mean to reset the date on focus event? Try to reset the date with `ng-focus` directive.
