### ISSUE TITLE
Allow null values

### ISSUE THREAD

**Issue by gsipos** [eight04/angular-datetime#9] opened 2015-10-20 14:22 UTC
Currently when the model is null, this directive replaces it to a new Date() or something.
So it seems its not possible to have empty input value

**Comment by eight04** [comment] 2015-10-24 07:34
This should be fixed in 1.3.0. Which version you are using?

**Comment by ericmdantas** [comment] 2016-01-14 10:22
I also need something like this.

In my case, I have a filter that the user may or may not fill the date input. If he does fill it, great, I'll use it for the filter; if not, I won't use it.

The thing is: when the user focus on the input, the date will be filled, but in my case, I'd need him to actually *try* to fill the date to do so. And not only that, I'd also need him to be able erase the date and filter without any info.

**Comment by eight04** [comment] 2016-01-16 02:37
@nguyentuevuong has made a patch that init date value on keypress: https://github.com/nguyentuevuong/angular-datetime/commit/921aa9623693bf597c5db84651f6162af2859a55. I can't determine which behavior is better for the users though.

To erase data, currently the only way is to Ctrl-A + Del. Chrome and IE10+ have implemented a little "x" button to clear the text field, but I think creating one ourselves is a bad idea.

I would put a clear button right after the input.

**Comment by betonetotbo** [comment] 2016-06-16 17:39
Hi, I created my own solution for this. The fix is attached to the plunker.

https://plnkr.co/edit/HiQlz7?p=preview

**Comment by eight04** [comment] 2016-06-17 05:52
Looks nice. I may consider:

1. Init date value on keypress when there is no `required` attr.
2. Init date value on focus when there is a `required` attr.
3. Create a placeholder like `{{parser.getText()}}`, if `placeholder` attr doesn't exists.

Or should we just use `init-on-focus` attr?

**Comment by betonetotbo** [comment] 2016-06-17 11:13
1. The date is already inited when you press any key, this is required to the mask work correctly I think.
2. This can be done, just change this`if (angular.isDefined(attrs["initOnFocus"]))` to this `if (angular.isDefined(attrs["initOnFocus"]) || angular.isDefined(attrs["required"]))`
3. I think this is not necessary, for this one is just to "set" the placeholder html attribute.

**Comment by eight04** [comment] 2016-06-18 14:35
The problem is that the user doesn't know what to do when the field is empty (if the value is not inited on focus). I think pressing a key to init the value is confusing to the user.

Let's see how Chrome implements datetime input. (With Taiwan locale)

1. When the field is empty, Chrome shows a placeholder on each part `year/month/date -- --:--`
2. When all parts are filled (e.g. `2016/06/18 PM 06:18`), you can get ISO date string from `input.value`

**Comment by betonetotbo** [comment] 2016-06-20 20:59
Answering

Yes, for me is confusing too. But simply focusing the input and init the date isn't a gut behavior too, and the another fact that I cannot clear the value to set it to null.

1. For this you can simply set the `placeholder` attribute
2. I think your are talking about the `<input type="date">`

**Comment by instantaphex** [comment] 2016-08-18 12:30
@eight04 I've got a use case where I have a form that filters data.  If the user is tabbing through the form to get to another field and happens to tab over a date input, it will initialize the date and the data will be filtered by date even if date isn't a required field.  Furthermore, after that, the user can't get rid of that date unless I implement a clear button.

I think at the very least you should have a flag to let people decide whether or not they want the field to auto initialize the date.  In some situations it can be helpful and a bit more clear, in other situations it can make the UI hard to use.

Will you consider implementing the fix that @betonetotbo provided, perhaps behind a flag?

**Comment by eight04** [comment] 2016-08-18 16:21
👍 
> If the user is tabbing through the form to get to another field and happens to tab over a date input, it will initialize the date and the data will be filtered by date even if date isn't a required field.

For this reason I guess we should make `init-on-focus` default to `false`.

I will start working on this and #36 in the next week.

**Comment by instantaphex** [comment] 2016-08-18 16:31
@eight04 in my case I was was able to put another directive on the element and hack around it with a bunch of event.preventImmediatePropagation () calls but I also had to force validation to pass on it because.  

This really is a great component but I feel like the restrictions need to be relaxed a bit.  Not being able to delete the value makes the input feel very unintuitive as a user.  Maybe it would be helpful as well to update the $viewValue to match the $modelValue when the user deletes a date node, even if that invalidates the input.  As a user I should be able to delete each node and then when all nodes are empty, I should have a valid input.

**Comment by eight04** [comment] 2016-08-18 23:04
How about to bind delete key or backspace to clear the input?

**Comment by instantaphex** [comment] 2016-08-19 21:33
That should work ok.  It would be ideal if you could delete one node at a time but anything that can be done to make it act somewhat like a normal input would be nice.

**Comment by eight04** [comment] 2016-08-25 11:54
Currently, I am working on something like this:

With format `yyyy-MM-dd` we get `2016-08-25`. 

If we delete the month part:
```
2016-[month]-25
```

If we set the model to null:
```
[year]-[month]-[day]
```

**Comment by eight04** [comment] 2016-09-01 07:12
Fixed in v4.0.0.

**Closed by eight04** 2016-09-01 07:12 UTC
